### ISSUE TITLE
发布JS文件

### ISSUE THREAD

**Issue by javow16437** [lzghzr/MDR_Proxy#1]
你好，
请问是否可以同时发布出JS文件(和Bin文件)，以便不熟悉Javascript的人使用。
万分感谢

**Comment by lzghzr** [comment]
咦? 好奇你们是怎么找到这个项目的

**Comment by javow16437** [comment]
在网上搜索尼耳机的固件降级，然后看到有人发布MDR_Proxy.zip的打包文件，就顺着名字找源头了

**Comment by lzghzr** [comment]
https://github.com/lzghzr/MDR_Proxy/releases/tag/0.1.0
