### ISSUE TITLE
I want to find wh1000xm4 more old grade of fireware

### ISSUE THREAD

**Issue by xhnybz** [lzghzr/MDR_Proxy#14]
I want to get fireware before ver2.5.0 of wh1000xm4,but i haven't get anything.Can you help me to find one,thank you very much. 
我想得到2.5.0版本以前的wh1000xm4固件，但是我实在是找不到，可以帮我找一个吗，十分感谢。

**Comment by lzghzr** [comment]
非常抱歉，所有我能找到的固件都在这个仓库里
