### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by morgenstern09** [lzghzr/MDR_Proxy#15]
Hello,

Sorry for writing in English... I am curious what does "[支持单文件多固件]" exactly mean? Translating to English it says "Support for single file multi-firmware", but I don't understand the meaning of this.

Thanks.

**Comment by lzghzr** [comment]
It means parsing multiple firmware from `info.xml`, not `.bin`.

**Comment by morgenstern09** [comment]
Oh, ok, I understand now. Thanks!
