### ISSUE TITLE
Support Android Sony Headphones v7.1.0

### ISSUE THREAD

**Issue by davidshen84** [lzghzr/MDR_Proxy#2]
Hi,

新的Android app好像不用原来的URL更新了。打开app后，代理完全没消息。但是手动访问`info.update.sony.net`是，代理还是可以记录消息。可以升级支持新的app吗？或者说明应该用哪个版本的app。

**Comment by chriscoderdr** [comment]
> info.update.sony.net

Did you find any solution to this?

**Comment by chriscoderdr** [comment]
> Hi,
> 
> 新的Android app好像不用原来的URL更新了。打开app后，代理完全没消息。但是手动访问`info.update.sony.net`是，代理还是可以记录消息。可以升级支持新的app吗？或者说明应该用哪个版本的app。

I found the poblem sony it's now using https, and the proxy it's ignoring it, but seems like they are still using the same url

**Comment by davidshen84** [comment]
I try to downgrade the Android to v3 and v4, but they won't work with the new firmware. The app simply won't register with the headphone and require upgrading to the latest version.

If it uses HTTPS, then the proxy needs to have a fake certificate and the phone needs to install that fake certificate and we also need to create a fake certificate for sony...that escalates quickly... :shrug:

**Comment by OspreyWarrior** [comment]
I had the same problem, but fixed it by downgrading the Headphones app to this version:

https://grimore.org/_media/fuss/hardware/sony/com.sony.songpal.mdr_4.1.0-41000_minapi21_armeabi_armeabi-v7a_nodpi_apkmirror.com.apk

**Comment by gbhtpago** [comment]
> I had the same problem, but fixed it by downgrading the Headphones app to this version:
> 
> https://grimore.org/_media/fuss/hardware/sony/com.sony.songpal.mdr_4.1.0-41000_minapi21_armeabi_armeabi-v7a_nodpi_apkmirror.com.apk

😩 can't do that on iPhone

**Comment by davidshen84** [comment]
Is that a modified APK? How reliable is the source?
