### ISSUE TITLE
WH-1000XM5更新2.0.2固件后使用最新headphones异常

### ISSUE THREAD

**Issue by HayashiNobunari** [lzghzr/MDR_Proxy#22]
我想把xm5回退1.1.1版本固件时发现点了更新后他的进度条开始飞速的往后退，到了大约-1500000%时直接闪退了 ，试了很多次均是这样，这是我的录屏：[https://pan.baidu.com/s/1lbjBUPoSA0GTSeuGzPCGuA?pwd=0w98](url)

**Comment by lzghzr** [comment]
app版本是10.1.0吗?

**Comment by xhnybz** [comment]
> app版本是10.1.0吗?

是的，我用的是从这里下载的版本

**Comment by lzghzr** [comment]
> 是的，我用的是从这里下载的版本

恐怕没什么好的解决方法

**Comment by HayashiNobunari** [comment]
算了，索尼用户要学会自适应 [哭笑]
