### ISSUE TITLE
Headphone not trigger the popup for upgrade process (downgrade)

### ISSUE THREAD

**Issue by KenyOS** [lzghzr/MDR_Proxy#27]
Hi I did a teste on your modified app of Headphone 10.3.0. I did a hotspot and enabled proxy to point to my PC. I tried everything but when I open the Headphone app it won't trigger the update process for me. I'm have a pair of LinkBud S. trying to downgrade away from 4.0.0 to 3.0.5_UPG_english_enc_secureboot.3458625ddc71b377f087dc9af0435b389d5bc980.bin. Could you help me? Also I disabled my firewall to make sure that port 8848 would be listened but no avail.

**Comment by lzghzr** [comment]
Did you put mdrproxy-key.pem and mdrproxy-cert.pem in the security folder?

**Comment by KenyOS** [comment]
I didn't before sorry I didn't saw the readme on security folder, so moved the files of cert on Headphone 10.3.0 zip to security folder of MDR proxy, I tried to restart the server again but when I open the Headphone still not show the update :c
I'll attach photo of my process. 
![image](https://github.com/lzghzr/MDR_Proxy/assets/5298786/341e43c1-ed2a-4489-93bd-96a17cd29270)
![image](https://github.com/lzghzr/MDR_Proxy/assets/5298786/ed9c9556-88b7-4fd7-9f35-e52c86759e52)
![image](https://github.com/lzghzr/MDR_Proxy/assets/5298786/efcfa410-a193-495b-985f-d69fd278bd94)
![image](https://github.com/lzghzr/MDR_Proxy/assets/5298786/2a4fa8cd-e756-41c9-85aa-5f1cf44fb6e9)
![image](https://github.com/lzghzr/MDR_Proxy/assets/5298786/4920480e-8d6d-4bf3-b715-dfee83cc25f9)

**Comment by lzghzr** [comment]
It should be 192.168.137.1

![307687774-ed5c4218-ca0f-4351-ae2e-72294a9fc62b_1](https://github.com/lzghzr/MDR_Proxy/assets/13391314/1fbec529-6aed-4451-a338-3080161bf185)

**Comment by KenyOS** [comment]
hahaha. OMG it's working now !! thanksss. Little mistake I just fast typed. Thank you again for helping me
