### ISSUE TITLE
number resolving

### ISSUE THREAD

**Issue by Halkjaer02** [lzghzr/MDR_Proxy#34]
How do I find the right firmware for my earbuds when the folders under the firmware folder is named with 4 numbers?
I use the WF-LS900N

**Comment by lzghzr** [comment]
you can find it at [Appendix](https://github.com/lzghzr/MDR_Proxy?tab=readme-ov-file#%E9%99%84%E5%BD%95-appendix)

**Comment by Halkjaer02** [comment]
Thank you so much
