### ISSUE TITLE
一些問題

### ISSUE THREAD

**Issue by muink** [lzghzr/MDR_Proxy#5]
感謝您提供的工具! 我有幾個問題希望得到解答
1. 使用playstore原版的MDR, 是不是需要在手機上安裝中間人證書, 具體怎麼操作
2. 如果持有的是列表里非https的設備, 還能否使用這個工具

**Comment by lzghzr** [comment]
1. 使用原版headphones 需要在`/system/etc/security/cacerts`中安装中间人证书, 也就是需要twrp
2. 列表里非https的设备也可以用, 只是非https设备还可以用headphones 6, 这样就可以使用http中间人, 不需要证书了

**Comment by muink** [comment]
感謝您的解答
我查了些資料, 安裝系統證書可以在magisked的手機上通過movecert模塊實現. 應該不是太大的問題
另外我有看到發佈區有一個`headphones_8000050_mdrproxy.apk` 這個是什麼用的呢
還有在切換版本的功能中 **01(日本版?)** 似乎是打了問號, 是使用上會有什麼問題嗎

**Comment by lzghzr** [comment]
’headphones_8000050_mdrproxy.apk’ 是[修改了xml](https://developer.android.com/training/articles/security-config)，添加了中间人证书, 所以不需要在系统中安装了, 提高了安全性,
01(日本版?) 是因为不清楚这个版本是什么地区的, 而且最新的固件已经把语音提醒独立出来了, 实际上00, 01, 02甚至03, 04的固件都是一样的

**Comment by muink** [comment]
剛剛嘗試了安裝`mdrproxy-cert.pem`
不論是轉成二進制DER格式的`mdrproxy-cert.crt`手動安裝
還是text的PEM格式的`c5ec74c2.0`放到`/system/etc/security/cacerts`
都失敗了, 一個顯示要密鑰才能安裝, 一個是安裝了在系統證書里沒有顯示
不知道哪裡出了問題

**Comment by lzghzr** [comment]
安装证书需要密钥是Android的限制, 和证书无关
`mdrproxy-cert.pem`是一个域名证书, 而不是CA证书, 我不清楚可不可以直接安装, CA证书在`headphones_8000050_mdrproxy.apk/res/raw/mdrproxy_ca.pem`

**Comment by muink** [comment]
已經裝好了,  確實是拿錯證書的問題, 用apk裡的CA證書安裝就沒問題

**Comment by muink** [comment]
還有個問題想問下，有沒有什麼辦法可以將指定的固件下載到本地保存，沒有固件的話，那不是功能3就沒法用嗎

**Comment by lzghzr** [comment]
> 還有個問題想問下，有沒有什麼辦法可以將指定的固件下載到本地保存，沒有固件的話，那不是功能3就沒法用嗎

没有办法, 索尼每次升级都会移除之前的固件访问权限, 想收集固件只能每次更新下载对应版本

**Comment by muink** [comment]
好吧, 那收集最新固件, 要怎麼操作呢

**Comment by lzghzr** [comment]
> 好吧, 那收集最新固件, 要怎麼操作呢

`mdr.ts`就是干这个用的

**Comment by muink** [comment]
`mdr.ts`要怎麼使用啊, 我完全不懂js, `ts-node mdr.ts`說缺失模塊
![image](https://user-images.githubusercontent.com/7929014/124478294-a15f0c00-ddd7-11eb-8c5e-6e40fa91b628.png)
