### ISSUE TITLE
运行程序到：已捕获到 /HP002/MDRID294802/info/info.xml 后无firmware下载

### ISSUE THREAD

**Issue by Goforfreedom** [lzghzr/MDR_Proxy#6]
您好，近来入手了WF-1000XM4，想试着刷国际版固件，执行cmd选择切换固件，到这一步就停住了，不知是何缘故。
P.S. 下载了您的MDR_Proxy后发现里面custom文件夹有一个WF-1000XM4_UPG_1.1.5_except_enc.bin文件，请问这个是哪个版本的固件呢？
非常感谢！
祝好。
![MDR](https://user-images.githubusercontent.com/57245602/124565785-fb61df00-de74-11eb-8152-9b6244fa374e.jpg)

**Comment by lzghzr** [comment]
采用MTK芯片的耳机 (包括WF-1000XM4) 都采用了新的OTA方式, 固件不再带有service id, 因此所有地区的固件一致, 切换区域这个功能在这些耳机上实际无效

**Comment by Goforfreedom** [comment]
> 采用MTK芯片的耳机 (包括WF-1000XM4) 都采用了新的OTA方式, 固件不再带有service id, 因此所有地区的固件一致, 切换区域这个功能在这些耳机上实际无效

谢谢您的回复，您程序里的WF-1000XM4_UPG_1.1.5_except_enc.bin文件是？是否还有方法通过刷固件的方法切换国际版。

**Comment by Goforfreedom** [comment]
> 采用MTK芯片的耳机 (包括WF-1000XM4) 都采用了新的OTA方式, 固件不再带有service id, 因此所有地区的固件一致, 切换区域这个功能在这些耳机上实际无效

如果选择强刷自定义固件并选择WF-1000XM4_UPG_1.1.5_except_enc.bin，手机端会提示有新固件。

**Comment by lzghzr** [comment]
> 谢谢您的回复，您程序里的WF-1000XM4_UPG_1.1.5_except_enc.bin文件是？是否还有方法通过刷固件的方法切换国际版。

自带的就是WF-1000XM4 1.1.5版本的固件, 因为我没有硬件, 所以不清楚是否可以通过其他方式更改service id

**Comment by Goforfreedom** [comment]
> > 谢谢您的回复，您程序里的WF-1000XM4_UPG_1.1.5_except_enc.bin文件是？是否还有方法通过刷固件的方法切换国际版。
> 
> 自带的就是WF-1000XM4 1.1.5版本的固件, 因为我没有硬件, 所以不清楚是否可以通过其他方式更改service id
> 

Thanks a million!
Good day!
