### ISSUE TITLE
切換區域失敗

### ISSUE THREAD

**Issue by muink** [lzghzr/MDR_Proxy#7]
耳機是狗圈2   用的是`headphones_8000050_mdrproxy.apk`和0.1.0版本的MDRProxy

使用切換到國際區功能, 在手機上把耳機升級到了2.0.2, 但是自定義鍵還是騰訊小薇是什麼情況啊

**Comment by lzghzr** [comment]
https://github.com/lzghzr/MDR_Proxy/issues/6#issuecomment-874565513

**Comment by muink** [comment]
好像確實有差別, 我觀察了info.xml文件, WI-1000X WH-1000XM2 WH-1000XM3這些老設備都有不止一條的ApplyOrder, 新設備只有一條ApplyOrder
``` xml
 <ApplyCondition ApplyOrder="1" Force="false">
 <ApplyCondition ApplyOrder="2" Force="false">
 <ApplyCondition ApplyOrder="3" Force="false">
```
然後固件的命名格式也不同老設備的是`with_stack`新的就沒有

所以真的沒有其他更改設備service id的方法了嗎

**Comment by qwerzl** [comment]
> 好像確實有差別, 我觀察了info.xml文件, WI-1000X WH-1000XM2 WH-1000XM3這些老設備都有不止一條的ApplyOrder, 新設備只有一條ApplyOrder
> 
> ```
>  <ApplyCondition ApplyOrder="1" Force="false">
>  <ApplyCondition ApplyOrder="2" Force="false">
>  <ApplyCondition ApplyOrder="3" Force="false">
> ```
> 
> 然後固件的命名格式也不同老設備的是`with_stack`新的就沒有
> 
> 所以真的沒有其他更改設備service id的方法了嗎

请问有找到什么其它的方法吗？我对比了WH1000XM5的00和02的固件，内容完全是相同的，看来通过更新固件的方式已经不能切换地区了...
