### ISSUE TITLE
headphones_8000050_mdrproxy.apk 丢失

### ISSUE THREAD

**Issue by lz233** [lzghzr/MDR_Proxy#8]
没看到 release 里 headphones_8000050_mdrproxy.apk 这个文件
请问还能提供下载吗

**Comment by lzghzr** [comment]
不再提供下载
[security](https://github.com/lzghzr/MDR_Proxy/tree/master/security) 目录下有个简单的说明，可以自己制作

**Comment by lz233** [comment]
好的
完毕了。
